### ISSUE TITLE
Servlet API 5 aka Jakarta support

### ISSUE THREAD

**Issue by gverran** [evolvedbinary/apache-xmlrpc#1]
Is it possible to add Servlet API 5 support to this library?  I am migrating over to Jetty 11 as to be future proofed and the XML-RPC from Apache is the only library that I have an incompatibility with hence how I found your library.  It would seem that based on the current trend with going from javax to jakarta, like Jetty 11, etc that a new version is created to support this, it seems that creating a v5 of this library would be the way to go.  These versions are maintained in parallel.

Is it possible that you can do this?

**Comment by adamretter** [comment]
@gverran I just came across the same issue myself, and so I have released version 5.0.0 to Maven Central to support `jakarta.servlet`
